language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

stages:
  - test
  - name: deploy
    if: tag IS present

matrix:
  include:
    - stage: deploy
      python: '3.6'
      env:
        - TWINE_USERNAME=__token__
        - secure: "yS8SItUNS+vBxLe6pzcLIYAzdlf5nT7DjlzHwIgd0qXOVoXYTtuXB9zgDWs5gmhMUlnipzucZ6P1/yQ0e36pAksv21iLAGHCRyo4QwyRSWdtevlYpSyYg3m4sWdHphgfzX55KhqGXkNPrJSF6cAZQ3F8bHHI7Cy80H5oEUL9vvmb9D9KgSKe3VofyMIB3t7CcE6BlWLesVWirpq+mLu5bDu4PQFqrvGtCyjXer7r9Dw2e5r/jOeaAt30eHzeHq7i4nwlaXHCbMytgs8YTNtCUMWEcJsvRJJW0WGWJ77/WTHt8XD2JNcQNEbgLm4YbebYDzzSsuEBd5S4tWjTBuaoWLhsCQKMgFytRTqi336rD6RkZs+rx4Tebx9iot2oMG+gs71L7qoBejvcShNHlaOj7dDGMmMC11QsvRLIF4b/ddP9lCmlOH6miY2vYx3uWmzKERwsDaAj/KaDUHkb1n1TnDccudOFg/BMFdl86uMuQFTQf2Rd3tP1ycYrRayZB8Kn7DgbLy/JZpiNngpxBkxORq5p3YlpY2r4nqMG2fMLDIMvjdf5mhOcveSSdDMdtBRrgcU1vzpkhzf+/sZfzhUWf5TBNO8Q5vpE/ZYFM8vrp10nKmBaM7MAsLADjW2nSHrKonQcOtM3QF3Xdb5GsVGUKqWZLouTCpcweIJ/ThmCgoE="
      before_install: {}
      install:
        - python3 -m pip install --upgrade pip setuptools
        - python3 -m pip install --upgrade twine wheel
      before_script: {}
      script:
        - python3 setup.py sdist bdist_wheel
        - twine check dist/*
        - twine upload --skip-existing dist/*

install:
  # Setup git to allow git operations.
  - git config --global user.name "Travis Test User"
  - git config --global user.email "planemo_test@galaxyproject.org"
  - pip install tox-travis coveralls

script: tox

after_success:
  - coveralls
