language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  # Setup git to allow git operations.
  - git config --global user.name "Travis Test User"
  - git config --global user.email "planemo_test@galaxyproject.org"
  - pip install tox-travis coveralls

script: tox

after_success:
  - coveralls
