name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.13']
        tox-env: ['lint', 'unit', 'tool-tests']
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: python3 -m pip install 'tox>=1.8.0'
      - name: Test
        run: tox -e ${{ matrix.tox-env }}
